### PR TITLE
[14.0][ADD] Add module account_ebics_automation

### PR DESCRIPTION
**Pull request by manengel**
Hello,
we have created a small module named account_ebics_automation which we think of as potentially useful for others.
It does fetch data from the configured banks automatically once per day.
We would like to receive your feedback on it and hope it can in fact be useful to you and other potentially interested individuals.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@manengel 
Thanks for this contribution but what you provide is a subset of the 'account_ebics_batch' module.
A simple cron job is not sufficient since you need to get a clear view on what has been downloaded or not (and in this case have the error log).
Hence please install the account_ebics_batch module for your automation needs.

**Comment by OSevangelist** [comment]
Hi @luc-demeyer (@manengel fyi) i think we missed to share a beer or even say hi last week (damned, next time). 

I eventually came across this again today and my folks at initOS pointed me to your comments on our pull request. Are you sure that your account_ebics_batch can also automate ebics import in a defined time frame (in order to avoid duplicate pulls, setting from and to times from the user interface), or was your suggestion rather: If you'd like to add this function, please add it to account_ebics_batch as this module covers more (like detailed error logging) as your module ? Thanks for your answer and guidance in advance.

Cheers Frederik

**Comment by luc-demeyer** [comment]
@OSevangelist 
The account_ebics_batch module adds a cron job and hence downloads at the time the cron job runs (typically at night).
If the user runs a second download manually during the day the ebics files downloaded at night will not be downloaded again (unless you force it via date from/to but you shouldn't do this regular operation but only if for some reason you have lost/deleted previous downloads.
We can schedule a short conf call if it's not clear or if I am missing somethiing.

**Comment by OSevangelist** [comment]
Hi @luc-demeyer thanks for clarifying so fast. The problem I see here, is, that in scenarios where time is decisive (like ours) only one daily batch job (at nights) would potentially lengthen the lead time to the customer up to about 24h. If i understood you right, the module doesn't keep track of what has actually been pulled and stored already but instead what should have been pulled (if the cron iteration run successfully). So underday pulls are not really covered (or at least almost certainly lead to doubled lines). Wouldn't it make sense to extend the module in a way that, even if you run it in batch mode at nights (regularly), allows to pull during the day manually (even twice or multiple times) and makes sure that the next consecutive batch / manual job only pulls from from after the last completed pull? I hope its clear what my concerns are and what my proposal would be but we can also have a brief chat on the matter tomorrow morning if you have time. If you consider my idea not valuable for the generic scenario (that the module should cover) let me know and we will try factor this out in a different extension "account_ebics_manual"

**Comment by luc-demeyer** [comment]
@OSevangelist 
The module is supposed to cover the scenarios you describe, no extra module is needed.
I propose we have a short conf call tomorrow morning and I'll explain.
Is 9:00 am ok for you ?
If yes, give me your e-mail address and I'll schedule a conf call.

**Comment by OSevangelist** [comment]
Hi @luc-demeyer i'll sent you my E-Mail over in a minute. Thanks for your willingness to do a brief call. I suggest to do it early next week as all relevant Persons involved in the case at our side are back from vacation. Just drop me 1 or 2 proposals for a 15min call. Thx a lot and have a great and relaxing weekend

**Comment by OSevangelist** [comment]
Hi @luc-demeyer one of my colleagues, namely @ortlam asked me on the status of this 'improvement'. If i recall our phone call regarding that topic right, you basically said that the bank counterpart implementation will basically care that you just download a given transaction once (unless you force it by explicit start_date and stop_date) I am not 100% sure but i think my colleague @fkantelberg experienced different things while communicating via EBICS and a German bank. Maybe @fkantelberg @ortlam you can describe better what happend in the project that let you come up with that improvement and add a comment here

**Comment by OSevangelist** [comment]
addendum: i think in our use case the bank offers intraday transaction updates via EBICS while the core implementation only makes sure that you won't get transactions until a certain date twice. This won't be sufficient considering user experience improvements provided from the bank side. Of course we might move to a entirely new banking PSD2 API but we believe our contribution would fix that gap. What do you think @luc-demeyer (@ortlam and @fkantelberg fyi cc)

**Comment by luc-demeyer** [comment]
Intraday -> camt52
Especially here adding a date from/to wouldn't help since it's intraday.
If you experiencing a doube retrieval of statements than your probelm will be elsewhere.
First question : did you pay the fintech license fee (cf. https://www.joonis.de/en/fintech/prices/) ? 
If not than you'll be in trouble.

The PSD2 API is an option, cf. https://github.com/OCA/bank-statement-import/tree/14.0/account_statement_import_online_ponto

The problem with PSD2 is that it is an aggregation service and usually the level of detail in the transactions is weaker than in camt statements.

**Pull request closed without merging**
