### PR TITLE
Change for using ebics in CH

### PR DESCRIPTION
**Pull request by davidwul**
I'm testing this ebics module, so far to be able to send receive file I had to add the CH ordre type.
I don't know if it's the best way. Tell me if not.

### CODE REVIEW

**Comment by davidwul** [comment]
I tested your proposal and the range seems to work correctly. I have a few questions and don't know if it's normal behavior:
Tell me, if I should ask them somewhere else:
1. I have two configurations (two accounts) when asking statement (Z53)  I receive both statements (even for the configuration not chosen)
2. when I choose no options (no dates, no formats) 
I have all statements that are downloaded again since the opening of the ebics contract.
it seems a new file is generated by the ebics server. On the contrary, the pain002 files are downloaded once only, no redownload seems possible.  
image

**Comment by joonis** [comment]
1. If your EBICS account has the permission for two bank accounts, you get the statements for both bank accounts. That is the normal behaviour.

2. A date range is only set if `date_from` and `date_to` are both specified:

```python
                            if date_from and date_to:
                                params = {'DateRange': {
                                    'Start': date_from,
                                    'End': date_to,
                                }}
```
Could this be the reason for the issue?

Please have a look at the difference between downloads with and without a specified date range:
https://www.joonis.de/en/fintech/doc/ebics/confirming_downloads/

**Comment by davidwul** [comment]
What is best, to add order type, file format specific to banks in an other module or do it in this base module?

**Comment by luc-demeyer** [comment]
@davidwul @joonis 
David, Thimo,
First of all thanks a lot for the work performed in this PR and my apologies for slow responsiveness on this.

I do have a couple of concerns that we need to sort out before I can merge this work.

1) DateRange

This PR changes the <DateRange> logic from >Start> & <End> optional into both required or both empty.
if I look to the ebics_orders.xsd than I do not find this requirement.
Since the fintech source code is not published I cannot look into the code to see how  it's handled but up till now nobody reported that the current approach didn't work.
Hence a question for @joonis 
can I restore the logic in https://github.com/Noviat/account_ebics/blob/e99b40244b452acaf400d42a45cb688d6b3cd9b3/account_ebics/wizard/ebics_xfer.py#L177:
kwargs = {k: v for k, v in params.items() if v}
followed by:
data = client.download(order_type, **kwargs)

2) Z01
@davidwul 
You have added Z01 to the order types without extending the '_file_format_methods' dictionary to parse the downloaded Payment Status file. Did you write and add-on module to make this info available in Odoo and e.g. act upon rejections ?
If yes: is it an option to add the handling of this format to the "_file_format_methods" in this module ?
If no; what about adding some logic to the ebics download wizard to allow the end user to specify also non-predefined order types (retrieved via the HAA order type).

3) Z52, Z53, Z54

Can you also extend the data/ebics_file_format.xml with these order types and data formats (and comments that these have been tested with rCH raiffeissen). This will make life easier for the next Odoo integrator that wants to connect to raiffeissen.

4) download of multiple statements form multiple bank accounts

I have added support for this in the 13.0 version of the account_ebics module but so far only for the french cfonb format.

cf. https://github.com/Noviat/account_ebics/blob/69859db0388b849d880b46be2b11f7904d40a6e9/account_ebics/models/ebics_file.py#L212

Before calling the standard Odoo 'account.bank.statement.import' wizard I first split the cfonb file into separate files per bank statement. After this I call the standard import wizard per statement.
Implementing the same logic for camt files should be straigthforward and would be a nice enhancement to this module. You'll have to change the Odoo multi-company logic though if you receive statements from multiple legal entities within a single ebics download (I used the new multi-company features of Odoo 13.0 to support this).

**Comment by joonis** [comment]
`Start` and `End` elements are both mandatory within a `DateRange`.
PyFinTech sets `Start` to '2000-01-01' or `End` to the current date if one of them is missing.
But if you pass `params` directly to the download method, it is left unchanged.

```python
                            if date_from or date_to:
                                params = {'DateRange': {
                                    'Start': date_from or '2000-01-01',
                                    'End': date_to or date.today().isoformat(),
                                }}
```

**Comment by luc-demeyer** [comment]
@davidwul 
Please have a look at https://github.com/Noviat/account_ebics/pull/24
I have taken a more general approach to support your requirements.
All File Formats in your EBICS contracts can now be added via the user interface to the EBICS File Formats.
You can also now define the 'Download Processing Method'.
These are pre-defined for e.g. camt.05x (if you have an available parser for Z01, let me know).
I have also added the most commonly used File Formats for CH.

Can you test and keep me posted ? 
I didn't do any testing on this specific PR, only (limited) testing on the 13.0 version of this PR, cf. https://github.com/Noviat/account_ebics/tree/13-generic-order_type from which I created this one via cherry-pick.

**Pull request closed without merging**
