### PR TITLE
[12.0] generic order type + CH File Formats

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by davidwul** [comment]
Thanks for this pull request, 
I will have a look at it, test it on our production environment. 
thanks for adding the CH file format.
I have a start of the pain002 parser, 
https://github.com/davidwul/account_ebics/tree/SwissModule%2Bpain002/account_ebics_payment_return
It needs improvements. For now it validates the payment order if the pain001 is ACC.
it should create a payment return using OCA module, but it seems the Raiffeisen bank don't send those info via a pain002.
I also created a "Swiss module" that adds other file format, that are specific to the Raiffeisen bank (ZZT & ZZQ) 
Each bank can define ZZ(X) as a their own format and could be different from bank to bank,

**Comment by luc-demeyer** [comment]
@davidwul 
I am surprised that Raiffeisen doesn't return pain.002. I looked to a couple of suisse EBICS docs this weekend and Z01 is always linked to pain.002.

Moving forward: 
I would like to add to the file format methods of the account_ebics module:

            'pain.002':
                {'process': self._process_pain002,
                 'unlink': self._unlink_pain002},

and

    <record id="ebics_ff_Z01" model="ebics.file.format">
      <field name="name">pain.002</field>
      <field name="type">down</field>
      <field name="order_type">Z01</field>
      <field name="download_process_method">pain.002</field>
      <field name="description">Payment status report for direct debit in format pain.002</field>
      <field name="suffix">psr.xml</field>
    </record>

whereby the _process_pain002 method calls the OCA account_payment_return_import module.

If Raiffeisen has their own format than you could make an  'account_payment_return_import_ch_raiffeisen' module that inherits upon the OCA module and adds that support (independent from the use of EBICS to retrieve the status reports). As soon as we know that the whole chain works we update the account_ebics README to point to the Raiffeissen Specific modules required to support Z01, ZZT, ZZQ, so that everyone can easily find them and hence can join the ecosystem to maintain these modules.

**Comment by davidwul** [comment]
I have tested with success the download and process of ZZT & ZZQ file with this branch. 
(ZZT is a Z53 and ZZQ is a Z54)  so it's working great, 
On my side you can go ahead and merge this.

Regarding pain002, 
It's a good option, I think it's what I did.
I have just added that the "successfully updated" is triggered by a payment return with the ACC status.

Raiffeisen return pain002, but I have not yet been able to test a real return (I processed only ACC) as they have no testing platform.

**Comment by luc-demeyer** [comment]
@davidwul 
I have added the Z01 placeholder logic as I suggested before.
Can you check if this small extension works ok.
I'll merge the code once I get your confirmation.

Concerning the payment return logic:
I propose that we consider adding general pain.002 logic based upon the OCA suite in a second phase (once your current Raiffeissen module is fully tested).

**Comment by davidwul** [comment]
Thanks a lot, these changes are ok, I was able to download statement, send payment order and retrieve pain002 with success.
for my side, you can go ahead and merge.
regarding importing pain002, you're right. I'll ping you when I have a module that is tested successfully with more usecases.

**Pull request merged**
